services:
  mysql:
    image: mysql:8.0
    container_name: support-ticket-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ai_support_ticket_db
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - support_ticket_mysql_data:/var/lib/mysql

volumes:
  support_ticket_mysql_data:
